#//
#// Copyright (c) 2019 Phoenix Contact GmbH & Co. KG. All rights reserved.
#// Licensed under the MIT. See LICENSE file in the project root for full license information.
#// SPDX-License-Identifier: MIT
#//
.AssembleLibraryTemplate:
 stage: assemble
 tags:
  - docker
  - debian-based
 script:
  - set -x
  - tools/assemble-library.sh -p ${PROJECTNAME} -t "${BUILD_HARDWARE}"
  - set +x
 artifacts:
  expire_in: 600 min
  paths:
   - deploy/