#//
#// Copyright (c) 2019 Phoenix Contact GmbH & Co. KG. All rights reserved.
#// Licensed under the MIT. See LICENSE file in the project root for full license information.
#// SPDX-License-Identifier: MIT
#//
.GenerateCodeTemplate:
 stage: generate
 tags:
  - docker
  - debian-based
 script:
  - ls -la build/$PROJECTNAME/src
  - set -x
  - tools/generate-code.sh -p ${PROJECTNAME}
  - set +x
  - ls -la build/$PROJECTNAME/src
  - ARR=($(plcncli get components -p build/${PROJECTNAME}/ | grep -oPe "(?<=\:)[A-Z][a-zA-Z0-9_]+"))
  - echo ${ARR[@]}
  - |
    for c in "${ARR[@]}"; \
    do \
    find build/$PROJECTNAME  -name "${c}.meta.cpp" | egrep '.*'; \
    find build/$PROJECTNAME -name "${c}ProgramProvider.hpp" | egrep '.*'; \
    find build/$PROJECTNAME  -name "${c}ProgramProvider.cpp" | egrep '.*'; \
    done
  - find build/$PROJECTNAME  -name "${PROJECTNAME}Library.hpp" | egrep '.*'
  - find build/$PROJECTNAME  -name "${PROJECTNAME}Library.cpp" | egrep '.*'
  - find build/$PROJECTNAME  -name "${PROJECTNAME}Library.meta.cpp"  | egrep '.*'

 cache:
  key: ${PROJECTNAME}
  paths:
   - build/${PROJECTNAME}
 artifacts:
   expire_in: 120 min
   paths:
    -  build/${PROJECTNAME}