# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

variables:
  BuildEnvironment: "dockerregistry.europe.phoenixcontact.com:8044/ima/plcncli/axcf2152/plcncli_axcf2152:2019.0"

stages:
  - build
  - test
  - deploy

.build:  
  stage: build
  tags: 
    - plcncli
  script: 
    - BuildOneProject.sh -p $PROJECTNAME -d $DIRECTORY -n $TARGETNAME -v $TARGETVERSION
  artifacts:
    when: on_success
    paths:
      - build/RELEASE
  variables:
    DIRECTORY: Examples

# ... include: 
.build_axcf:
  extends: .build
  image: $BuildEnvironment

programcomponentinteraction:
  extends: .build_axcf
  variables:
    PROJECTNAME: ProgramComponentInteraction


# run tests using the binary built before
test:
  image: VirtualPLCnextTestEnvironment
  stage: test
  script: 

deploy_Libraries:
  dependencies:
  - programcomponentinteraction
