.# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: dockerregistry.europe.phoenixcontact.com/docker:stable

stages:
  - build
  - test
  - deploy

tags: 
  - docker
  - debian-based

variables:
  BuildEnvironment: "dockerregistry.europe.phoenixcontact.com:8044/ima/plcncli/axcf2152/plcncli_axcf2152:2019.0"


#Build Template
.build:  
  stage: build
  tags: 
    - plcncli
  script: 
    - BuildOneProject.sh -p $PROJECTNAME -d $DIRECTORY -n $TARGETNAME -v $TARGETVERSION
  artifacts:
    when: on_success
    paths:
      - build/RELEASE

#Build Environments
.build_axcf:
  extends: .build
  image: $BuildEnvironment
  variables:
    TARGETNAME: "AXCF2152"
    TARGETVERSION: "2019.0"

.build_RFC:
  extends: .build
  image: $BuildEnvironment
  variables:
    TARGETNAME: "RFC4072"
    TARGETVERSION: "2019.0"

### Example ProgramComponentInteraction###
.programcomponentinteraction:
  variables:
    PROJECTNAME: ProgramComponentInteraction
    DIRECTORY: Examples
    
pci_axc:
  extends: 
    - .programcomponentinteraction
    - .build_axcf

pci_rfc:
  extends: 
    - .programcomponentinteraction
    - .build_rfc

# run tests using the binary built before


deploy_Libraries:
  dependencies:
  - pci_axc
  - pci_rfc
